name: "Tensorflow"

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'     
        required: false
        default: false

jobs:
  Train:
    name: "Train"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image
        run: make buildTrainImage

      - name: Run debug tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Train
        run: make ciTrain

      - name: Upload training model
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Battlegrounds-Duel.h5
          path: Battlegrounds-Duel.h5

      - name: Upload training data image
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: graph.png
          path: graph.png

      - name: Upload image
        id: upload-image
        uses: McCzarny/upload-image@v1.0.0
        if: always()
        with:
          path: graph.png
          uploadMethod: imgbb
          apiKey: '${{ secrets.IMGBB_API_KEY }}'

      - name: Output to job steps
        if: always()
        run: echo -e "# Training Graph\n\n![Training Graph](${{ steps.upload-image.outputs.url }})" >> $GITHUB_STEP_SUMMARY
