name: "Tensorflow"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Train:
    name: "Train"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image
        run: make buildTrainImage

      - name: Setup graph.png
        run: -|
          touch graph.png
          chmod 666 graph.png

      - name: Train
        run: make ciTrain

      - name: Upload training data image
        uses: actions/upload-artifact@v3
        with:
          name: graph.png
          path: graph.png
