name: "Tensorflow"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Train:
    name: "Train"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image
        run: make buildTrainImage

      - name: Train
        run: make ciTrain

      - name: Upload training data image
        uses: actions/upload-artifact@v3
        with:
          name: graph.png
          path: graph.png

      - name: Upload image
        id: upload-image
        uses: McCzarny/upload-image@v1.0.0
        with:
          path: graph.png
          uploadMethod: imgbb
          apiKey: '${{ secrets.IMGBB_API_KEY }}'

      - name: Output to job steps
        run: echo "![Training Graph](${{ steps.upload-image.outputs.url }})" >> $GITHUB_STEP_SUMMARY
